# Post conversion modification of adoc files.
# Ensure the target_dir variable is set in the playbook that imports this.
- name: add passthrough to schema rule
  ansible.builtin.replace:
    path: "{{ target_rules_dir }}schema.adoc"
    regexp: 'vars/\*.yml'
    replace: '+vars/*.yml+'
- name: add passthrough to var_naming rule
  ansible.builtin.replace:
    path: "{{ target_rules_dir }}var_naming.adoc"
    regexp: 'underscore \`_\` character'
    replace: 'underscore `+_+` character'